services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      NODE_ENV: production

    volumes:
      - sqlite_data:/app/db

    expose:
      - "3000"

  nginx:
    build:
      context: ./yimby-ranking-client
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

volumes:
  sqlite_data:
